# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        main:
            pattern: ^/
            anonymous: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


